### Data Loading and Cleaning

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
annex1 = pd.read_csv('annex1.csv')  # items
annex2 = pd.read_csv('annex2.csv')  # sales transactions
annex3 = pd.read_csv('annex3.csv')  # wholesale prices
annex4 = pd.read_csv('annex4.csv')  # loss rates

In [ ]:
annex1.head() #this is to check the type of data that was imported for each file

,Item Code,Item Name,Category Code,Category Name
0,102900005115168,Niushou Shengcai,1011010101,Flower/Leaf Vegetables
1,102900005115199,Sichuan Red Cedar,1011010101,Flower/Leaf Vegetables
2,102900005115625,Local Xiaomao Cabbage,1011010101,Flower/Leaf Vegetables
3,102900005115748,White Caitai,1011010101,Flower/Leaf Vegetables
4,102900005115762,Amaranth,1011010101,Flower/Leaf Vegetables

In [ ]:
annex2.head() #this is to check the type of data that was imported for each file

,Date,Time,Item Code,Quantity Sold (kilo),Unit Selling Price (RMB/kg),Sale or Return,Discount (Yes/No)
0,2020-07-01,09:15:07.924,1.029000e+14,0.396,7.6,sale,No
1,2020-07-01,09:17:27.295,1.029000e+14,0.849,3.2,sale,No
2,2020-07-01,09:17:33.905,1.029000e+14,0.409,7.6,sale,No
3,2020-07-01,09:19:45.450,1.029000e+14,0.421,10.0,sale,No
4,2020-07-01,09:20:23.686,1.029000e+14,0.539,8.0,sale,No

In [ ]:
annex3.head() #this is to check the type of data that was imported for each file

         Date        Item Code  Wholesale Price (RMB/kg)
0  2020-07-01  102900005115762                      3.88
1  2020-07-01  102900005115779                      6.72
2  2020-07-01  102900005115786                      3.19
3  2020-07-01  102900005115793                      9.24
4  2020-07-01  102900005115823                      7.03

In [ ]:
annex4.head() #this is to check the type of data that was imported for each file

         Item Code                 Item Name  Loss Rate (%)
0  102900005115168          Niushou Shengcai           4.39
1  102900005115199         Sichuan Red Cedar          10.46
2  102900005115250  Xixia Black Mushroom (1)          10.80
3  102900005115625     Local Xiaomao Cabbage           0.18
4  102900005115748              White Caitai           8.78

In [ ]:
annex1.info() #this checks the data type of each file that was imported

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 251 entries, 0 to 250
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Item Code      251 non-null    int64
 1   Item Name      251 non-null    object
 2   Category Code  251 non-null    int64
 3   Category Name  251 non-null    object
dtypes: int64(2), object(2)
memory usage: 8.0+ KB

In [ ]:
annex2.info() #this checks the data type of each file that was imported

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35320 entries, 0 to 35319
Data columns (total 7 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Date                         35320 non-null  object
 1   Time                         35320 non-null  object
 2   Item Code                    35319 non-null  float64
 3   Quantity Sold (kilo)         35319 non-null  float64
 4   Unit Selling Price (RMB/kg)  35319 non-null  float64
 5   Sale or Return               35319 non-null  object
 6   Discount (Yes/No)            35319 non-null  object
dtypes: float64(3), object(4)
memory usage: 1.9+ MB

In [ ]:
annex3.info() #this checks the data type of each file that was imported

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55982 entries, 0 to 55981
Data columns (total 3 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Date                      55982 non-null  object
 1   Item Code                 55982 non-null  int64
 2   Wholesale Price (RMB/kg)  55982 non-null  float64
dtypes: float64(1), int64(1), object(1)
memory usage: 1.3+ MB

In [ ]:
annex4.info() #this checks the data type of each file that was imported

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 251 entries, 0 to 250
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Item Code      251 non-null    int64
 1   Item Name      251 non-null    object
 2   Loss Rate (%)  251 non-null    float64
dtypes: float64(1), int64(1), object(1)
memory usage: 6.0+ KB

Annex 2 and Annex 3 have a the date data type in a different format so i have to change it to a date format

In [ ]:
annex2['Date'] = pd.to_datetime(annex2['Date'])
annex3['Date'] = pd.to_datetime(annex3['Date'])

Now i want to check if the data has null or not for each file i have uploaded

In [ ]:
annex1.isnull().sum()

Item Code        0
Item Name        0
Category Code    0
Category Name    0
dtype: int64

In [ ]:
annex2.isnull().sum()

date                           0
time                           0
item_code                      1
quantity_sold_(kilo)           1
unit_selling_price_(rmb/kg)    1
sale_or_return                 1
discount_(yes/no)              1
dtype: int64

In [ ]:
annex3.isnull().sum()

Date                        0
Item Code                   0
Wholesale Price (RMB/kg)    0
dtype: int64

In [ ]:
annex4.isnull().sum()

Item Code        0
Item Name        0
Loss Rate (%)    0
dtype: int64

Reshaping the coloumn headers so as to maintain consistency

In [ ]:
annex2.columns = annex2.columns.str.strip().str.replace(' ', '_').str.lower()
annex3.columns = annex3.columns.str.strip().str.replace(' ', '_').str.lower()
annex4.columns = annex4.columns.str.strip().str.replace(' ', '_').str.lower()
annex1.columns = annex1.columns.str.strip().str.replace(' ', '_').str.lower()

We have now checked all files to understand what our files contain so what is next is to merge the data together into one big data using the join function so analysis and insights drawn can be a bit more effective
We start by identifying the fact table and we join the dimension table to the fact table

In [ ]:
sales = annex2.merge(annex1, on='item_code', how='left') # adds item name + category
sales = sales.merge(annex3, on=['item_code', 'date'], how='left') # adds wholesale price
sales = sales.merge(annex4, on='item_code', how='left') # adds loss rate

In [ ]:
sales.head()

,date,time,item_code,quantity_sold_(kilo),unit_selling_price_(rmb/kg),sale_or_return,discount_(yes/no),item_name_x,category_code,category_name,wholesale_price_(rmb/kg),item_name_y,loss_rate_(%)
0,2020-07-01,09:15:07.924,1.029000e+14,0.396,7.6,sale,No,Paopaojiao (Jingpin),1.011011e+09,Capsicum,4.32,Paopaojiao (Jingpin),7.08
1,2020-07-01,09:17:27.295,1.029000e+14,0.849,3.2,sale,No,Chinese Cabbage,1.011010e+09,Flower/Leaf Vegetables,2.10,Chinese Cabbage,22.27
2,2020-07-01,09:17:33.905,1.029000e+14,0.409,7.6,sale,No,Paopaojiao (Jingpin),1.011011e+09,Capsicum,4.32,Paopaojiao (Jingpin),7.08
3,2020-07-01,09:19:45.450,1.029000e+14,0.421,10.0,sale,No,Shanghaiqing,1.011010e+09,Flower/Leaf Vegetables,7.03,Shanghaiqing,14.43
4,2020-07-01,09:20:23.686,1.029000e+14,0.539,8.0,sale,No,Caixin,1.011010e+09,Flower/Leaf Vegetables,4.60,Caixin,13.70

In [ ]:
sales.describe()

,date,item_code,quantity_sold_(kilo),unit_selling_price_(rmb/kg),category_code,wholesale_price_(rmb/kg),loss_rate_(%)
count,35320,3.531900e+04,35319.000000,35319.000000,3.531900e+04,35319.000000,35319.000000
mean,2020-07-16 20:30:09.377123584,1.029111e+14,0.404726,10.177828,1.011010e+09,6.031219,10.885262
min,2020-07-01 00:00:00,1.029000e+14,-2.000000,0.100000,1.011010e+09,1.400000,2.480000
25%,2020-07-09 00:00:00,1.029000e+14,0.251000,7.000000,1.011010e+09,4.250000,7.080000
50%,2020-07-17 00:00:00,1.029000e+14,0.368000,9.000000,1.011010e+09,5.330000,10.180000
75%,2020-07-25 00:00:00,1.029000e+14,0.501000,12.000000,1.011011e+09,6.920000,13.820000
max,2020-08-02 00:00:00,1.069561e+14,4.274000,39.800000,1.011011e+09,29.540000,29.250000
std,NaN,2.122772e+11,0.237950,4.808287,2.588010e+02,2.701571,4.744083

In [ ]:
sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35320 entries, 0 to 35319
Data columns (total 13 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   date                         35320 non-null  datetime64[ns]
 1   time                         35320 non-null  object
 2   item_code                    35319 non-null  float64
 3   quantity_sold_(kilo)         35319 non-null  float64
 4   unit_selling_price_(rmb/kg)  35319 non-null  float64
 5   sale_or_return               35319 non-null  object
 6   discount_(yes/no)            35319 non-null  object
 7   item_name_x                  35319 non-null  object
 8   category_code                35319 non-null  float64
 9   category_name                35319 non-null  object
 10  wholesale_price_(rmb/kg)     35319 non-null  float64
 11  item_name_y                  35319 non-null  object
 12  loss_rate_(%)                35319 non-null  float64
dtypes: datetime64[ns](1), float64(6), object(6)
memory usage: 3.5+ MB

In [ ]:
sales.to_csv('sales.csv', index=False)
#exports the just merged data and makes it easy for sharing

In [ ]:
sales['revenue']= sales['quantity_sold_(kilo)'] * sales['unit_selling_price_(rmb/kg)']
sales['revenue']

0        3.0096
1        2.7168
2        3.1084
3        4.2100
4        4.3120
          ...
35315    3.5120
35316    6.2160
35317    3.2080
35318    4.7120
35319       NaN
Name: revenue, Length: 35320, dtype: float64

In [ ]:
sales['margin'] = sales['unit_selling_price_(rmb/kg)'] - sales['wholesale_price_(rmb/kg)']
sales['margin']

0        3.28
1        1.10
2        3.28
3        2.97
4        3.40
         ...
35315    2.72
35316    4.58
35317    3.56
35318    3.78
35319     NaN
Name: margin, Length: 35320, dtype: float64

In [ ]:
sales['effective_margin'] = sales['margin'] * (1 - sales['loss_rate_(%)'] / 100)
sales['effective_margin']

0        3.047776
1        0.855030
2        3.047776
3        2.541429
4        2.934200
           ...
35315    2.463504
35316    4.155892
35317    3.170536
35318    3.395196
35319         NaN
Name: effective_margin, Length: 35320, dtype: float64

## Sales Performance

In [ ]:
total_revenue = round(sales['revenue'].sum(),2)
total_revenue
#total revenue generated

np.float64(128885.37)

In [ ]:
print(round(sales['quantity_sold_(kilo)'].sum(),2))
#total quantity sold

14294.53

In [ ]:
print(round(sales['revenue'].mean(),2))
#average sales

3.65

In [ ]:
sales.groupby('date')['revenue'].sum()

date
2020-07-01    3472.0136
2020-07-02    3456.5429
2020-07-03    3384.7701
2020-07-04    4394.8624
2020-07-05    4471.5748
2020-07-06    3382.9821
2020-07-07    3226.8223
2020-07-08    3463.7944
2020-07-09    3198.0202
2020-07-10    3548.1649
2020-07-11    5182.3877
2020-07-12    5334.7254
2020-07-13    3415.1306
2020-07-14    3542.5183
2020-07-15    3522.9482
2020-07-16    3692.5499
2020-07-17    3594.8699
2020-07-18    5064.9799
2020-07-19    6046.9371
2020-07-20    3544.2292
2020-07-21    3615.3756
2020-07-22    4270.6872
2020-07-23    3653.9129
2020-07-24    3395.0753
2020-07-25    4773.8778
2020-07-26    5448.1701
2020-07-27    3976.0203
2020-07-28    3404.9242
2020-07-29    4030.2351
2020-07-30    3672.4544
2020-07-31    3368.7367
2020-08-01    4398.3128
2020-08-02    1936.7614
Name: revenue, dtype: float64

## Product-Level Insights

In [ ]:
sales.groupby('category_name')['category_name'].count().sort_values(ascending=False)
#most sold productcategory

category_name
Flower/Leaf Vegetables         14914
Capsicum                        8200
Edible Mushroom                 5471
Cabbage                         3374
Solanum                         2473
Aquatic Tuberous Vegetables      887
Name: category_name, dtype: int64

In [ ]:
sales.groupby('category_name')['revenue'].sum().sort_values(ascending=False)
#category with most revenue

category_name
Flower/Leaf Vegetables         51728.3659
Capsicum                       24346.1607
Edible Mushroom                20373.6597
Cabbage                        17388.0299
Solanum                        10048.4732
Aquatic Tuberous Vegetables     5000.6783
Name: revenue, dtype: float64

In [ ]:
sales.groupby('item_name_x')['quantity_sold_(kilo)'].sum().sort_values(ascending=False).head()
#top 10 selling items

item_name_x
Paopaojiao (Jingpin)    1125.073
Yunnan Shengcai          995.429
Yunnan Lettuces          961.209
Broccoli                 873.385
Chinese Cabbage          724.257
Name: quantity_sold_(kilo), dtype: float64

In [ ]:
#items performing below average
item_sales = sales.groupby('item_name_x')['revenue'].sum()  #revenue of all items
avg_sales = item_sales.mean() #average sales of all item
below_avg_items = item_sales[item_sales < avg_sales].sort_values(ascending=True) #items below average
print(below_avg_items)

item_name_x
Niushou Youcai                       1.7216
Ping Mushroom                        5.5120
The Crab Flavor Mushroom (2)        14.0000
Nanguajian                          39.0000
Haixian Mushroom (Bag) (1)          39.5000
Lotus (Ea)                          50.4000
Red Hot Peppers                     61.3252
Needle Mushroom (Bag) (1)           97.5000
Spinach                            144.1980
The White Mushroom (2)             324.2000
Yellow Xincai (1)                  384.5883
Bell Pepper (1)                    398.5373
Jigu Mushroom (Bunch)              403.6000
Honghu Lotus Root                  502.8648
Foreign Garland Chrysanthemum      503.7986
Dongmenkou Xiaobaicai              554.0198
7 Colour Pepper (1)                575.2688
Jigu Mushroom (1)                  695.1316
The Red Bell Pepper (1)            722.7891
Muercai                            795.9650
Green Hot Peppers                  811.3041
High Melon (1)                     887.8898
Haixian Mushroom (1)               941.3516
Amaranth                           959.9410
Red Hang Pepper                   1109.2881
Red Pepper (1)                    1588.9667
Green Line Pepper                 1880.8029
Millet Pepper                     2332.0614
Green Eggplant (1)                2408.3229
Zhuyecai                          2483.7167
Name: revenue, dtype: float64

In [ ]:
item_sales.sort_values(ascending=True).head(10) #another way to check for underperforming items

item_name_x
Niushou Youcai                    1.7216
Ping Mushroom                     5.5120
The Crab Flavor Mushroom (2)     14.0000
Nanguajian                       39.0000
Haixian Mushroom (Bag) (1)       39.5000
Lotus (Ea)                       50.4000
Red Hot Peppers                  61.3252
Needle Mushroom (Bag) (1)        97.5000
Spinach                         144.1980
The White Mushroom (2)          324.2000
Name: revenue, dtype: float64

## Profitability

In [ ]:
sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35320 entries, 0 to 35319
Data columns (total 16 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   date                         35320 non-null  datetime64[ns]
 1   time                         35320 non-null  object
 2   item_code                    35319 non-null  float64
 3   quantity_sold_(kilo)         35319 non-null  float64
 4   unit_selling_price_(rmb/kg)  35319 non-null  float64
 5   sale_or_return               35319 non-null  object
 6   discount_(yes/no)            35319 non-null  object
 7   item_name_x                  35319 non-null  object
 8   category_code                35319 non-null  float64
 9   category_name                35319 non-null  object
 10  wholesale_price_(rmb/kg)     35319 non-null  float64
 11  item_name_y                  35319 non-null  object
 12  loss_rate_(%)                35319 non-null  float64
 13  revenue                      35319 non-null  float64
 14  margin                       35319 non-null  float64
 15  effective_margin             35319 non-null  float64
dtypes: datetime64[ns](1), float64(9), object(6)
memory usage: 4.3+ MB

In [ ]:
sales['profit_per_item']= sales['unit_selling_price_(rmb/kg)'] - sales['wholesale_price_(rmb/kg)']
print(sales['profit_per_item'])
#profit per item

0        3.28
1        1.10
2        3.28
3        2.97
4        3.40
         ...
35315    2.72
35316    4.58
35317    3.56
35318    3.78
35319     NaN
Name: profit_per_item, Length: 35320, dtype: float64

In [ ]:
#products that are most profitable
sales.groupby('category_name')['profit_per_item'].sum().sort_values(ascending=False)

category_name
Flower/Leaf Vegetables         45160.83
Capsicum                       43360.77
Edible Mushroom                31362.48
Cabbage                        14389.64
Solanum                         7127.88
Aquatic Tuberous Vegetables     5052.46
Name: profit_per_item, dtype: float64

In [ ]:
sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35320 entries, 0 to 35319
Data columns (total 17 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   date                         35320 non-null  datetime64[ns]
 1   time                         35320 non-null  object
 2   item_code                    35319 non-null  float64
 3   quantity_sold_(kilo)         35319 non-null  float64
 4   unit_selling_price_(rmb/kg)  35319 non-null  float64
 5   sale_or_return               35319 non-null  object
 6   discount_(yes/no)            35319 non-null  object
 7   item_name_x                  35319 non-null  object
 8   category_code                35319 non-null  float64
 9   category_name                35319 non-null  object
 10  wholesale_price_(rmb/kg)     35319 non-null  float64
 11  item_name_y                  35319 non-null  object
 12  loss_rate_(%)                35319 non-null  float64
 13  revenue                      35319 non-null  float64
 14  margin                       35319 non-null  float64
 15  effective_margin             35319 non-null  float64
 16  profit_per_item              35319 non-null  float64
dtypes: datetime64[ns](1), float64(10), object(6)
memory usage: 4.6+ MB

In [ ]:
#overall profit margin
total_profit = round(sales['profit_per_item'].sum(),2)
total_profit
profit_margin = round(total_profit / total_revenue* 100, 2)

In [ ]:
print(profit_margin)

113.63

## Time Based Analysis

In [ ]:
daily_sales = sales.groupby('date')['revenue'].sum()  #Everything here speak to daily sales
highest_day = daily_sales.idxmax()
highest_day_value = daily_sales.max()

In [ ]:
print(highest_day) #day with highest sales

2020-07-19 00:00:00

In [ ]:
print(highest_day_value) #highest sales value

6046.9371

In [ ]:
print(daily_sales)

date
2020-07-01    3472.0136
2020-07-02    3456.5429
2020-07-03    3384.7701
2020-07-04    4394.8624
2020-07-05    4471.5748
2020-07-06    3382.9821
2020-07-07    3226.8223
2020-07-08    3463.7944
2020-07-09    3198.0202
2020-07-10    3548.1649
2020-07-11    5182.3877
2020-07-12    5334.7254
2020-07-13    3415.1306
2020-07-14    3542.5183
2020-07-15    3522.9482
2020-07-16    3692.5499
2020-07-17    3594.8699
2020-07-18    5064.9799
2020-07-19    6046.9371
2020-07-20    3544.2292
2020-07-21    3615.3756
2020-07-22    4270.6872
2020-07-23    3653.9129
2020-07-24    3395.0753
2020-07-25    4773.8778
2020-07-26    5448.1701
2020-07-27    3976.0203
2020-07-28    3404.9242
2020-07-29    4030.2351
2020-07-30    3672.4544
2020-07-31    3368.7367
2020-08-01    4398.3128
2020-08-02    1936.7614
Name: revenue, dtype: float64

In [ ]:
sales['month'] = sales['date'].dt.to_period('M') #month with highest sales

monthly_sales = sales.groupby('month')['revenue'].sum()

highest_month = monthly_sales.idxmax()

In [ ]:
print(highest_month) #month with highest sales

2020-07

In [ ]:
# seasonal trends
monthly_sales = sales.groupby('month')['revenue'].sum()
print(monthly_sales)

month
2020-07    122550.2935
2020-08      6335.0742
Freq: M, Name: revenue, dtype: float64

In [ ]:
sales.to_csv('sales_cleaned.csv', index=False)